name: docker context
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container: node:18-alpine@sha256:f8f6e351b184217e007918f27f821cb005a12826452cd6d7399920231a47ffac
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v3
      - run: echo "Running stuff"
      - uses: actions/setup-node@v3
        with:
          #node-version: '18'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json
      - run: node -v
      - run: npm -v
      - run: npx -v
      - run: npm clean-install
      - run: npm start
      - run: pwd
      - run: id
      - run: echo $TOKEN
        env:
          TOKEN: ${{ secrets.SUPER_SECRET }}

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        id: buildx_setup
        uses: docker/setup-buildx-action@v2

      - name: Pull tests
        uses: actions/checkout@v3

      - name: Non-push build only
        uses: docker/build-push-action@v4
        with:
          push: false
          load: true
          context: client
          file: client/docker/Dockerfile
          builder: ${{ steps.buildx_setup.outputs.name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: testag


