name: Dummy CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      ASIS: ${{ secrets.DEEZ }}/nuts
      DEF: ${{ secrets.DEEZ || 'ligma' }}/nuts
      PUSH_TRUE: ${{ github.event_name == 'push' }}

    steps:
      - name: env test
        run: |
          echo $ASIS
          echo $DEF
          echo "ENV_TRUE=${{ fromJSON(env.PUSH_TRUE) }}" >> $GITHUB_ENV
          echo "ENV_FALSE=${{ !fromJSON(env.PUSH_TRUE) }}" >> $GITHUB_ENV
      - name: Run a one-line script
        run: echo Hello, World!

      - name: run test
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install selenium pytest
          which pytest
          cat <<EOF > brol.py
          import unittest

          class TestDeezNuts(unittest.TestCase):
            def test_quickmaff(self):
              self.assertEqual(2, 2)

            def test_fail(self):
              self.assertEqual(2, 3)

            def test_multi(self):
              with self.subTest():
                self.assertEqual(1,1)
                self.assertEqual(1,2)
            def test_ass(self):
              assert 1==1, 'ok'
              assert 1==2, 'ded'
              assert 1==1, 're-ok'

          if __name__ == '__main__':
            unittest.main(verbosity=2)
          EOF
          pytest -v brol.py

          python3 <<EOF
          import unittest
          from selenium import webdriver
          from selenium.webdriver.common.by import By
          from selenium.webdriver.firefox.options import Options

          class TestBdxInterface(unittest.TestCase):
            @classmethod
            def setUpClass(cls):
              ops = Options()
              ops.add_argument("--headless")
              cls.driver = webdriver.Firefox(options=ops)
              cls.driver.get("https://www.github.com")
              cls.driver.get_full_page_screenshot_as_file("deez_nuts.png")

            def test_quickmaff(self):
              self.assertEqual(2, 2)

            @classmethod
            def tearDownClass(cls):
              cls.driver.close()

          if __name__ == '__main__':
            unittest.main(verbosity=2)

          EOF

      - name: save screen
        uses: actions/upload-artifact@v3
        with:
          name: selenium-screen
          path: deez_nuts.png

      - name: branch name
        run: |
          env
          echo ref ${{ github.ref }}
          echo head ${{ github.head_ref }}
          echo base ${{ github.base_ref }}

      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Test multi env
        run: |
          cat << EOF | python -- >> $GITHUB_ENV

          print('CUSTOM_VAR1=V1')
          print('CUSTOM_VAR2=V2')

          EOF

      - name: check env
        if: env.PUSH_TRUE == 'true'
        run: env

      - name: cat hotfix_crash.txt
        if: env.PUSH_TRUE != 'true'
        run: cat hotfix_crash.txt
