name: Dummy CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      ASIS: ${{ secrets.DEEZ }}/nuts
      DEF: ${{ secrets.DEEZ || 'ligma' }}/nuts
      PUSH_TRUE: ${{ github.event_type == 'push' }}
      ENV_TRUE: ${{ env.PUSH_TRUE }}
      ENV_FALSE: ${{ ! env.PUSH_TRUE }}

    steps:
      - name: env test
        run: |
          echo $ASIS
          echo $DEF
          echo "ENV_TRUE=${{ env.PUSH_TRUE }}" >> $GITHUB_ENV
          echo "ENV_FALSE=${{ !env.PUSH_TRUE }}" >> $GITHUB_ENV
      - name: Run a one-line script
        run: echo Hello, World!

      - name: branch name
        run: |
          env
          echo ref ${{ github.ref }}
          echo head ${{ github.head_ref }}
          echo base ${{ github.base_ref }}

      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Test multi env
        run: |
          cat << EOF | python -- >> $GITHUB_ENV

          print('CUSTOM_VAR1=V1')
          print('CUSTOM_VAR2=V2')

          EOF

      - name: check env
        run: env

      - name: cat hotfix_crash.txt
        run: cat hotfix_crash.txt
