name: pls fail
on:
  workflow_dispatch:

jobs:
  should-fail:
    runs-on: ubuntu-latest
    steps:
      - name: step should fail
        run: |
          echo "::error ::Deez nuts"
          exit 1
